import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// Dev-only stub for /api/generate-plan. The real handler is a Vercel
// serverless function (api/generate-plan.js) that isn't served by plain
// `vite`/`npm run dev` — it only runs when deployed to Vercel or via
// `vercel dev`. This plugin's configureServer hook only fires for Vite's
// own dev server, so it has zero effect on `vite build` / production.
const mockGeneratePlan = () => ({
  name: 'mock-generate-plan-api',
  configureServer(server) {
    server.middlewares.use('/api/generate-plan', (req, res, next) => {
      if (req.method !== 'POST') return next()
      const mockPlan = {
        title: 'Mock 8-Week Strength & Conditioning Plan (local dev only)',
        summary: 'This plan was generated by a local Vite dev stub, not the real API — use it to check UI/layout without an Anthropic API key or Vercel functions.',
        schedule: ['Monday', 'Wednesday', 'Friday'],
        weeks: 8,
        weeks_breakdown: [
          { phase: 'Weeks 1-2 — Foundation', focus: 'Learn the movement patterns with moderate volume.' },
          { phase: 'Weeks 3-5 — Build', focus: 'Progressive overload on the main lifts.' },
          { phase: 'Weeks 6-8 — Peak', focus: 'Highest intensity block, deload in the final week.' },
        ],
        workouts: [
          {
            day: 'Monday', name: 'Push Day: Chest, Shoulders & Triceps', type: 'Strength', duration: '50 min',
            warmup: '5 min band pull-aparts, arm circles, and light incline push-ups',
            cooldown: '5 min static stretching — chest doorway stretch, cross-body shoulder stretch',
            exercises: [
              { name: 'Incline Dumbbell Press', sets: '3', reps: '10-12', rest: '90s', note: 'Mock data for local testing.' },
              { name: 'Cable Lateral Raise', sets: '3', reps: '12-15', rest: '60s', note: '' },
            ],
          },
          {
            day: 'Wednesday', name: 'Pull Day: Back & Biceps', type: 'Strength', duration: '50 min',
            warmup: '5 min dead hangs and scapular pull-ups',
            cooldown: '5 min lat stretch and doorway chest stretch',
            exercises: [
              { name: 'Lat Pulldown', sets: '4', reps: '8-10', rest: '90s', note: '' },
              { name: 'Seated Cable Row', sets: '3', reps: '10-12', rest: '75s', note: '' },
            ],
          },
          {
            day: 'Friday', name: 'Legs Day', type: 'Lower Body', duration: '55 min',
            warmup: '5 min bodyweight squats and leg swings',
            cooldown: '5 min quad and hamstring stretch',
            exercises: [
              { name: 'Goblet Squat', sets: '4', reps: '8-10', rest: '120s', note: '' },
              { name: 'Romanian Deadlift', sets: '3', reps: '10-12', rest: '90s', note: '' },
            ],
          },
        ],
        nutrition_tips: [
          'Aim for 1.6-2g of protein per kg of bodyweight, spread across 3-4 meals.',
          'Prioritize whole food carbs around your training window for energy.',
          'Stay hydrated — aim for 3L of water daily, more on training days.',
        ],
        motivation_strategy: 'Mock motivation text for local dev testing — not generated by the real AI.',
        weekly_checkin: 'Mock weekly check-in text for local dev testing — not generated by the real AI.',
      }
      res.setHeader('Content-Type', 'application/json')
      res.end(JSON.stringify({ content: [{ type: 'text', text: JSON.stringify(mockPlan) }] }))
    })
  },
})

// Dev-only stub for /api/grade-workout, same rationale as mockGeneratePlan above —
// exercises the "Grade my routine" UI locally without Anthropic/Vercel functions.
const mockGradeWorkout = () => ({
  name: 'mock-grade-workout-api',
  configureServer(server) {
    server.middlewares.use('/api/grade-workout', (req, res, next) => {
      if (req.method !== 'POST') return next()
      const mockGrade = {
        summary: 'Mock grade result from a local Vite dev stub, not the real API — use it to check UI/layout without an Anthropic API key or Vercel functions.',
        fixes: [
          { issue: 'Barbell Upright Row is labeled as a medial delt move but it primarily trains rear delts and traps.', fix: 'Swap in a Cable Lateral Raise if medial delt width is the goal.', exercise: 'Barbell Upright Row' },
          { issue: 'Chest is trained on 4 of the 5 days, well past the advanced 16-22 sets/week range, while legs get one short session.', fix: 'Cut chest volume roughly in half and add a second lower-body day.', exercise: null },
          { issue: 'Cable Crossover is programmed but no cable machine was listed as available equipment.', fix: 'Replace with a Dumbbell Fly, which uses equipment already on hand.', exercise: 'Cable Crossover' },
          { issue: 'No rep ranges or plan to add weight/reps over time anywhere in the routine.', fix: 'Add a target rep range per exercise and a rule for when to increase load.', exercise: null },
        ],
      }
      res.setHeader('Content-Type', 'application/json')
      res.end(JSON.stringify({ content: [{ type: 'text', text: JSON.stringify(mockGrade) }] }))
    })
  },
})

// https://vite.dev/config/
export default defineConfig({
  plugins: [react(), mockGeneratePlan(), mockGradeWorkout()],
})
