const LAST_UPDATED = "July 20, 2025";
const CONTACT_EMAIL = "fitplanai.support@gmail.com";

export const TermsOfService = () => (
  <div style={{ maxWidth: 720, margin: "0 auto", padding: "2rem 1.25rem", fontFamily: "'Inter', system-ui, sans-serif", color: "#374151", lineHeight: 1.7 }}>
    <h1 style={{ fontSize: "1.5rem", fontWeight: 800, color: "#111827", marginBottom: "0.25rem" }}>Terms of Service</h1>
    <p style={{ fontSize: "0.82rem", color: "#9CA3AF", marginBottom: "2rem" }}>Last updated: {LAST_UPDATED}</p>

    <Section title="1. Acceptance of Terms">
      By accessing or using FitPlan AI ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, please do not use the Service.
    </Section>

    <Section title="2. Not Medical Advice">
      FitPlan AI is an AI-powered fitness planning tool intended for general informational and educational purposes only. The workout plans, nutrition tips, and any other content generated by the Service do not constitute medical advice, diagnosis, or treatment.
      <br /><br />
      You should always consult a qualified healthcare professional or certified fitness trainer before beginning any new exercise program, especially if you have any pre-existing medical conditions, injuries, or health concerns. FitPlan AI is not a licensed medical provider and cannot replace professional medical judgment.
    </Section>

    <Section title="3. Assumption of Risk">
      Physical exercise carries inherent risks, including but not limited to injury, muscle strain, cardiovascular events, and other health complications. By using the Service, you acknowledge and accept these risks. FitPlan AI, its owner Xavier Hernandez, and any affiliated parties are not responsible for any injury, illness, loss, or damage arising from your use of the generated workout plans or any other content provided by the Service.
    </Section>

    <Section title="4. User Accounts">
      You must create an account to use the Service. You are responsible for maintaining the confidentiality of your login credentials and for all activity that occurs under your account. You agree to provide accurate information during registration and to notify us immediately of any unauthorized use of your account.
    </Section>

    <Section title="5. Acceptable Use">
      You agree not to use the Service to:
      <ul style={{ paddingLeft: "1.5rem", marginTop: "0.5rem" }}>
        <li>Share your account access with others</li>
        <li>Attempt to reverse engineer, copy, or resell the Service</li>
        <li>Use the Service for any unlawful purpose</li>
        <li>Interfere with or disrupt the Service or its servers</li>
      </ul>
    </Section>

    <Section title="6. Intellectual Property">
      The Service, including its design, code, and branding, is owned by FitPlan AI. The workout plans generated for you are for your personal use only and may not be redistributed or sold.
    </Section>

    <Section title="7. Limitation of Liability">
      To the fullest extent permitted by law, FitPlan AI and its owner shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of or inability to use the Service. In no event shall our total liability exceed the amount you paid for the Service in the past 12 months.
    </Section>

    <Section title="8. Changes to Terms">
      We reserve the right to update these Terms at any time. Continued use of the Service after changes are posted constitutes acceptance of the new Terms.
    </Section>

    <Section title="9. Contact">
      If you have questions about these Terms, contact us at <a href={`mailto:${CONTACT_EMAIL}`} style={{ color: "#16A34A" }}>{CONTACT_EMAIL}</a>.
    </Section>
  </div>
);

export const PrivacyPolicy = () => (
  <div style={{ maxWidth: 720, margin: "0 auto", padding: "2rem 1.25rem", fontFamily: "'Inter', system-ui, sans-serif", color: "#374151", lineHeight: 1.7 }}>
    <h1 style={{ fontSize: "1.5rem", fontWeight: 800, color: "#111827", marginBottom: "0.25rem" }}>Privacy Policy</h1>
    <p style={{ fontSize: "0.82rem", color: "#9CA3AF", marginBottom: "2rem" }}>Last updated: {LAST_UPDATED}</p>

    <Section title="1. Information We Collect">
      We collect the following information when you use FitPlan AI:
      <ul style={{ paddingLeft: "1.5rem", marginTop: "0.5rem" }}>
        <li><strong>Account information:</strong> your email address and password (stored securely via Supabase)</li>
        <li><strong>Fitness information:</strong> the goals, schedule, equipment, and preferences you enter when generating a plan</li>
        <li><strong>Generated plans:</strong> the workout plans created for you, stored to your account</li>
      </ul>
      We do not collect payment card details directly — payments are handled by third-party processors.
    </Section>

    <Section title="2. How We Use Your Information">
      We use your information to:
      <ul style={{ paddingLeft: "1.5rem", marginTop: "0.5rem" }}>
        <li>Generate and save your personalized fitness plans</li>
        <li>Maintain and improve the Service</li>
        <li>Communicate with you about your account</li>
      </ul>
      We do not sell your personal data to third parties.
    </Section>

    <Section title="3. AI Processing">
      The fitness information you provide is sent to Anthropic's Claude API to generate your workout plan. This data is processed in accordance with <a href="https://www.anthropic.com/privacy" target="_blank" rel="noopener noreferrer" style={{ color: "#16A34A" }}>Anthropic's Privacy Policy</a>. We do not store your inputs beyond what is needed to generate and save your plan.
    </Section>

    <Section title="4. Data Storage">
      Your account and plan data is stored securely using Supabase, a third-party database provider. Data is protected using industry-standard security measures including row-level security policies that ensure only you can access your own data.
    </Section>

    <Section title="5. Data Retention">
      We retain your data for as long as your account is active. You may request deletion of your account and associated data at any time by contacting us.
    </Section>

    <Section title="6. Your Rights">
      You have the right to:
      <ul style={{ paddingLeft: "1.5rem", marginTop: "0.5rem" }}>
        <li>Access the personal data we hold about you</li>
        <li>Request correction of inaccurate data</li>
        <li>Request deletion of your data</li>
        <li>Withdraw consent at any time by deleting your account</li>
      </ul>
      To exercise these rights, contact us at <a href={`mailto:${CONTACT_EMAIL}`} style={{ color: "#16A34A" }}>{CONTACT_EMAIL}</a>.
    </Section>

    <Section title="7. Cookies">
      We use session cookies to keep you logged in. We do not use tracking or advertising cookies.
    </Section>

    <Section title="8. Children's Privacy">
      The Service is not directed at children under 13. We do not knowingly collect personal information from children under 13.
    </Section>

    <Section title="9. Changes to This Policy">
      We may update this Privacy Policy from time to time. We will notify you of significant changes by posting the new policy on this page with an updated date.
    </Section>

    <Section title="10. Contact">
      If you have questions about this Privacy Policy, contact us at <a href={`mailto:${CONTACT_EMAIL}`} style={{ color: "#16A34A" }}>{CONTACT_EMAIL}</a>.
    </Section>
  </div>
);

const Section = ({ title, children }) => (
  <div style={{ marginBottom: "1.75rem" }}>
    <h2 style={{ fontSize: "1rem", fontWeight: 700, color: "#111827", marginBottom: "0.5rem" }}>{title}</h2>
    <p style={{ margin: 0, fontSize: "0.9rem" }}>{children}</p>
  </div>
);