const LAST_UPDATED = "August 18, 2026";
const CONTACT_EMAIL = "fitplanai.support@gmail.com";

export const TermsOfService = () => (
  <div style={{ maxWidth: 720, margin: "0 auto", padding: "2rem 1.25rem", fontFamily: "var(--sans)", color: "var(--ink-soft)", lineHeight: 1.7 }}>
    <h1 style={{ fontFamily: "var(--display)", fontSize: "1.5rem", fontWeight: 600, letterSpacing: "-0.02em", color: "var(--ink)", marginBottom: "0.25rem" }}>Terms of Service</h1>
    <p style={{ fontSize: "0.82rem", color: "var(--faint)", marginBottom: "2rem" }}>Last updated: {LAST_UPDATED}</p>

    <Section title="1. Acceptance of Terms">
      By accessing or using FitPlan AI ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, please do not use the Service.
    </Section>

    <Section title="2. Not Medical Advice">
      FitPlan AI is an AI-powered fitness planning tool intended for general informational and educational purposes only. The workout plans, nutrition tips, and any other content generated by the Service do not constitute medical advice, diagnosis, or treatment.
      <br /><br />
      You should always consult a qualified healthcare professional or certified fitness trainer before beginning any new exercise program, especially if you have any pre-existing medical conditions, injuries, or health concerns. FitPlan AI is not a licensed medical provider and cannot replace professional medical judgment.
    </Section>

    <Section title="3. Assumption of Risk">
      Physical exercise carries inherent risks, including but not limited to injury, muscle strain, cardiovascular events, and other health complications. By using the Service, you acknowledge and accept these risks. FitPlan AI, its owner Xavier Hernandez, and any affiliated parties are not responsible for any injury, illness, loss, or damage arising from your use of the generated workout plans or any other content provided by the Service.
    </Section>

    <Section title="4. User Accounts">
      You must create an account to use the Service. You are responsible for maintaining the confidentiality of your login credentials and for all activity that occurs under your account. You agree to provide accurate information during registration and to notify us immediately of any unauthorized use of your account.
    </Section>

    <Section title="5. Acceptable Use">
      You agree not to use the Service to:
      <ul style={{ paddingLeft: "1.5rem", marginTop: "0.5rem" }}>
        <li>Share your account access with others</li>
        <li>Attempt to reverse engineer, copy, or resell the Service</li>
        <li>Use the Service for any unlawful purpose</li>
        <li>Interfere with or disrupt the Service or its servers</li>
      </ul>
    </Section>

    <Section title="6. Intellectual Property">
      The Service, including its design, code, and branding, is owned by FitPlan AI. The workout plans generated for you are for your personal use only and may not be redistributed or sold.
    </Section>

    <Section title="7. Payments and Refunds">
      Paid purchases ("Unlock" and additional plan generations) are one-time payments processed by Stripe. All sales are final and non-refundable, except where required by applicable law. Access to what you purchase (additional plan generations, saving, and PDF export) is granted immediately upon successful payment.
      <br /><br />
      By completing a purchase, you expressly request that we begin providing the purchased digital content and features immediately, and you acknowledge that doing so means you lose any statutory right of withdrawal or cooling-off period that might otherwise apply to online purchases of digital content.
    </Section>

    <Section title="8. Disclaimer of Warranties">
      The Service is provided "as is" and "as available," without warranties of any kind, whether express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, or non-infringement. We do not warrant that the Service will be uninterrupted, error-free, or that AI-generated content will be accurate or suitable for your specific circumstances.
    </Section>

    <Section title="9. Limitation of Liability">
      To the fullest extent permitted by law, FitPlan AI and its owner shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of or inability to use the Service. In no event shall our total liability exceed the amount you paid for the Service in the past 12 months.
    </Section>

    <Section title="10. Termination">
      We may suspend or terminate your access to the Service at any time, with or without notice, if we believe you have violated these Terms or misused the Service. You may stop using the Service and request deletion of your account at any time by contacting us.
    </Section>

    <Section title="11. Changes to Terms">
      We reserve the right to update these Terms at any time. Continued use of the Service after changes are posted constitutes acceptance of the new Terms.
    </Section>

    <Section title="12. Contact">
      If you have questions about these Terms, contact us at <a href={`mailto:${CONTACT_EMAIL}`} style={{ color: "var(--accent)" }}>{CONTACT_EMAIL}</a>.
    </Section>
  </div>
);

export const PrivacyPolicy = () => (
  <div style={{ maxWidth: 720, margin: "0 auto", padding: "2rem 1.25rem", fontFamily: "var(--sans)", color: "var(--ink-soft)", lineHeight: 1.7 }}>
    <h1 style={{ fontFamily: "var(--display)", fontSize: "1.5rem", fontWeight: 600, letterSpacing: "-0.02em", color: "var(--ink)", marginBottom: "0.25rem" }}>Privacy Policy</h1>
    <p style={{ fontSize: "0.82rem", color: "var(--faint)", marginBottom: "2rem" }}>Last updated: {LAST_UPDATED}</p>

    <Section title="1. Information We Collect">
      We collect the following information when you use FitPlan AI:
      <ul style={{ paddingLeft: "1.5rem", marginTop: "0.5rem" }}>
        <li><strong>Account information:</strong> your email address and password (stored securely via Supabase)</li>
        <li><strong>Fitness information:</strong> the goals, schedule, equipment, and preferences you enter when generating a plan</li>
        <li><strong>Generated plans:</strong> the workout plans created for you, stored to your account</li>
        <li><strong>Progress data:</strong> the weekly check-ins you submit, including which exercises you completed and the reps/weight you log</li>
        <li><strong>Payment information:</strong> handled entirely by Stripe (see Section 6) — we do not collect or store your card details</li>
      </ul>
    </Section>

    <Section title="2. How We Use Your Information">
      We use your information to:
      <ul style={{ paddingLeft: "1.5rem", marginTop: "0.5rem" }}>
        <li>Generate, adjust, and save your personalized fitness plans</li>
        <li>Track your progress and tailor recommendations based on your check-ins</li>
        <li>Maintain and improve the Service</li>
        <li>Communicate with you about your account</li>
      </ul>
      We do not sell your personal data to third parties.
    </Section>

    <Section title="3. AI Processing">
      The fitness and progress information you provide is sent to Anthropic's Claude API to generate, adjust, or grade your workout plans. This data is processed in accordance with <a href="https://www.anthropic.com/privacy" target="_blank" rel="noopener noreferrer" style={{ color: "var(--accent)" }}>Anthropic's Privacy Policy</a>. We do not store your inputs beyond what is needed to generate, adjust, and save your plan.
    </Section>

    <Section title="4. Exercise Data Lookup">
      When you view or swap an exercise, the exercise name and equipment are sent to ExerciseDB (via RapidAPI), a third-party service, to look up a matching demonstration GIF. This lookup does not include your account information or any other personal data.
    </Section>

    <Section title="5. Data Storage">
      Your account and plan data is stored securely using Supabase, a third-party database provider. Data is protected using industry-standard security measures including row-level security policies that ensure only you can access your own data.
    </Section>

    <Section title="6. Payments">
      Payments are processed by Stripe. When you make a purchase, Stripe collects and processes your payment details directly — we never receive or store your card information. Stripe's use of your data is governed by <a href="https://stripe.com/privacy" target="_blank" rel="noopener noreferrer" style={{ color: "var(--accent)" }}>Stripe's Privacy Policy</a>.
    </Section>

    <Section title="7. Data Retention">
      We retain your data for as long as your account is active. You may request deletion of your account and associated data at any time by contacting us.
    </Section>

    <Section title="8. Your Rights">
      You have the right to:
      <ul style={{ paddingLeft: "1.5rem", marginTop: "0.5rem" }}>
        <li>Access the personal data we hold about you</li>
        <li>Request correction of inaccurate data</li>
        <li>Request deletion of your data</li>
        <li>Withdraw consent at any time by deleting your account</li>
      </ul>
      To exercise these rights, contact us at <a href={`mailto:${CONTACT_EMAIL}`} style={{ color: "var(--accent)" }}>{CONTACT_EMAIL}</a>.
    </Section>

    <Section title="9. Local Storage">
      We use your browser's local storage (not cookies) to keep you logged in, and to temporarily save an in-progress plan or form you haven't submitted yet so it survives a page refresh or a trip through checkout — that temporary cache expires automatically within 24 hours. This data stays on your device and is not used for tracking or advertising. We do not use tracking or advertising cookies.
    </Section>

    <Section title="10. Children's Privacy">
      The Service is not directed at children under 13. We do not knowingly collect personal information from children under 13.
    </Section>

    <Section title="11. Changes to This Policy">
      We may update this Privacy Policy from time to time. We will notify you of significant changes by posting the new policy on this page with an updated date.
    </Section>

    <Section title="12. Contact">
      If you have questions about this Privacy Policy, contact us at <a href={`mailto:${CONTACT_EMAIL}`} style={{ color: "var(--accent)" }}>{CONTACT_EMAIL}</a>.
    </Section>
  </div>
);

const Section = ({ title, children }) => (
  <div style={{ marginBottom: "1.75rem" }}>
    <h2 style={{ fontSize: "1rem", fontWeight: 700, color: "var(--ink)", marginBottom: "0.5rem" }}>{title}</h2>
    <p style={{ margin: 0, fontSize: "0.9rem" }}>{children}</p>
  </div>
);